# Generated by Django 3.1.7 on 2021-10-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('Mobile', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('Worker_Type', models.CharField(max_length=20)),
                ('Rate', models.CharField(max_length=20)),
            ],
        ),
    ]
